name: Deploy Database Migrations

on:
  push:
    branches:
      - main  # Triggers only when pushing to main branch

jobs:
  migrate:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flyway
        run: |
          curl -O https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/10.0.0/flyway-commandline-10.0.0-linux-x64.tar.gz
          tar -xvzf flyway-commandline-10.0.0-linux-x64.tar.gz
          sudo mv flyway-10.0.0 /usr/local/flyway
          echo "/usr/local/flyway" >> $GITHUB_PATH

      - name: Run Flyway Migrations on Production
        env:
          FLYWAY_URL: jdbc:postgresql://${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          flyway -user="$FLYWAY_USER" -password="$FLYWAY_PASSWORD" -url="$FLYWAY_URL" -locations=filesystem:./migrations migrate